data <- read.table("household_power_consumption.txt", header = TRUE, sep = ";")
data.sub <- data[data$Date == "1/2/2007" | data$Date == "2/2/2007", ]
data.sub$Date <- as.character(data.sub$Date)
data.sub$Time <- as.character(data.sub$Time)
time <- paste(data.sub$Date, data.sub$Time, sep = " ")
time <- strptime(time, "%d/%m/%Y%X")
data.sub <- cbind(data.sub, time)
data.sub$Global_active_power <- as.character(data.sub$Global_active_power)
data.sub$Global_active_power <- as.numeric(data.sub$Global_active_power)
data.sub$Voltage <- as.character(data.sub$Voltage)
data.sub$Voltage <- as.numeric(data.sub$Voltage)
data.sub$Sub_metering_1 <- as.character(data.sub$Sub_metering_1)
data.sub$Sub_metering_1 <- as.numeric(data.sub$Sub_metering_1)
data.sub$Sub_metering_2 <- as.character(data.sub$Sub_metering_2)
data.sub$Sub_metering_2 <- as.numeric(data.sub$Sub_metering_2)
data.sub$Global_reactive_power <- as.character(data.sub$Global_reactive_power)
data.sub$Global_reactive_power <- as.numeric(data.sub$Global_reactive_power)
png("plot4.png", width = 480, height = 480, units = "px")
par(mfrow = c(2,2))
with(data.sub, plot(time, Global_active_power, type = "l", xlab = "", ylab = "Global Active Power"))
with(data.sub, plot(time, Voltage, type = "l", xlab = "datetime", ylab = "Voltage"))
with(data.sub, plot(time, Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering"))
with(data.sub, lines(time, Sub_metering_2, col = "red"))
with(data.sub, lines(time, Sub_metering_3, col = "blue"))
legend(x = "topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), lwd = 1)
with(data.sub, plot(time, Global_reactive_power, type = "l", xlab = "datetime", ylab = "Global_reactive_power"))
dev.off()